name: test.yml
on: [push]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: yarn
    - name: Run tests
      run: yarn lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: yarn
    - name: Run tests
      run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: [analyse, test]
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Pull Vercel secrets
      run: vercel pull --yes --environment:production --token=${{ secrets.VERCEL_TOKEN }}
    - name: Build artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
    - name: Deploy to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

